import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabaseClient';
import { Category } from '@/types';

export async function POST(req: Request) {
    const { action, hours } = await req.json();

    if (action === 'FAST_FORWARD') {
        const shiftAmount = (hours || 1) * 60 * 60 * 1000;

        // Fetch open complaints
        const { data: complaints } = await supabase.from('complaints').select('*').in('status', ['OPEN', 'IN_PROGRESS']);

        if (!complaints) return NextResponse.json({ message: 'No active complaints' });

        for (const c of complaints) {
            const newDeadline = new Date(new Date(c.sla_deadline).getTime() - shiftAmount).toISOString();

            await supabase.from('complaints').update({ sla_deadline: newDeadline }).eq('id', c.id);
        }

        // Check for breaches
        await fetch(new URL('/api/cron', req.url));

        return NextResponse.json({ success: true, message: `Fast forwarded ${hours} hours` });
    }

    if (action === 'GENERATE_BURST') {
        const locations = ['Block A', 'Block B', 'Mess Hall', 'Common Room'];
        const categories: Category[] = ['Electricity', 'Water', 'Hygiene', 'Safety'];

        const promises = Array(3).fill(0).map(async () => {
            const cat = categories[Math.floor(Math.random() * categories.length)];
            const loc = locations[Math.floor(Math.random() * locations.length)];

            // Re-use POST logic by calling internal function or just re-implementing insert here.
            // For sim speed, we insert directly but won't trigger full priority logic unless we duplicate code or refactor to shared util.
            // Let's just create raw complaints.

            const { data: complaint } = await supabase.from('complaints').insert({
                title: `Simulated: ${cat} Issue`,
                description: 'Generated by Burst Mode',
                category: cat,
                severity: 'Medium', // Default
                priority_score: 30,
                location: loc,
                sla_deadline: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
                status: 'OPEN'
            }).select().single();

            if (complaint) {
                await supabase.from('events').insert({
                    type: 'ComplaintRaised',
                    payload: { id: complaint.id, message: 'Burst Simulation Event' }
                });
            }
        });

        await Promise.all(promises);
        return NextResponse.json({ success: true, message: 'Generated 3 complaints' });
    }

    return NextResponse.json({ error: 'Invalid Action' });
}
